# This should compile on Linux and DJGPP without changes

CC=i686-w64-mingw32-gcc
FLAGS=-Wall -DALLEGRO_STATICLINK -I/home/trent/code/win-include
LIBS=icon.res -L/home/trent/code/win-lib -lalleg -lddraw -ldsound -ldinput8 -ldxguid -lgdi32 -lole32 -lwinmm
EXE=ballz

ballz: ballz.c ballz.h datnames.h
	$(CC) $(FLAGS) ballz.c -o $(EXE) $(LIBS) -static -static-libgcc -static-libstdc++ -Wl,--subsystem,windows

clean:
	@rm -f ballz $(EXE) *.o *~ core
